#!/bin/sh
#
# Load all necessary st modules
# 
# chkconfig: S 9 0
#

echo "init frontpanel"
modprobe proton
modprobe simu_button
mknod -m 644 /dev/vfd c 147 0
#mknod -m 644 /dev/hdmi_cec c 149 0
modprobe e2_proc

   echo "init stmfb"
   modprobe stmcore-display-stx7109c3
   modprobe stmfb display0=1920x1080-32@50:12m:pal:yuv:yuv

   echo "LOADING MODULES"   
   echo "ЗАГРУЗКА" >/dev/vfd

   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init AVS"
   modprobe avs type=stv6418

   modprobe mmelog
   modprobe mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   modprobe pseudocard

   modprobe fe-core demod=stb0899 tuner=stb6100
   modprobe pti waitMS=20 videoMem=10240
   modprobe stm_monitor
   modprobe stmsysfs
   modprobe stmdvb

   modprobe player2 discardlateframe=0
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen
   modprobe smartcard debug=100
   modprobe bpamem
   #modprobe cec
   #echo "init oc"
   #modprobe cpu_frequ
   #405mhz
   #echo 25609 > /proc/cpu_frequ/pll0_ndiv_mdiv
   #echo 1 > /proc/cpu_frequ/pll1_fdma_bypass
   #15110 = 266mhz
   #25609 = 300mhz
   #9475 = 333mhz
   #31241 = 366mhz
   #22790 = 400mhz
   #3841 = 405mhz

  /var/bin/swap start
  /var/bin/opkg.sh &
  
  showiframe -p /boot/bootlogo.mvi &
  stfbcontrol a 0

	stfbcontrol a 255
	echo " e2 "
	/var/bin/on_gmt.sh &
	/var/bin/emustarter.sh &

